#161967091 view and edit profiles
andela/ah-code-titans-frontend pull request #15
Opened 2019-01-17 12:41 UTC by denomash

#### What does this PR do?

- Users should be able to view and edit their profiles

#### Description of Task to be completed?

-  users can have access to my profile.
- a user can edit his/her profile to his/her preference.

#### How should this be manually tested?

- Clone this repo from the terminal

```
git clone https://github.com/andela/ah-code-titans-frontend.git
```

- cd into the projects folder
```
cd ah-code-titans-frontend
```

- Then Run `git fetch ft-view-edit-profiles-16196709` 

- checkout the branch: `ft-view-edit-profiles-16196709`

- Install all dependencies by running: `npm install` or `yarn`

- Run the app by running: `npm start`

#### What are the relevant pivotal tracker stories?
[#161967091](https://www.pivotaltracker.com/story/show/161967091)

**Checklist**

- [x] My code follows the style guidelines of this project

- [x] I have performed a self-review of my own code

- [x] My changes generate no new warnings

####Screenshot
**VIEWING A PROFILE**
<img width="1169" alt="screenshot 2019-01-17 at 15 38 34" src="https://user-images.githubusercontent.com/41957873/51319454-27533500-1a6e-11e9-8a4f-e687623c2c02.png">

**UPDATING A PROFILE**
<img width="1169" alt="screenshot 2019-01-17 at 15 38 44" src="https://user-images.githubusercontent.com/41957873/51319461-2fab7000-1a6e-11e9-933c-4bd18784e8aa.png">

2019-01-24 17:45 UTC, Darius-Ndubi approved these changes
👍

2019-01-24 18:01 UTC, Bryan-Cee approved these changes
👍 LGTM

2019-01-24 18:14 UTC, davishooly approved these changes

2019-01-24 19:23 UTC, bettblake08 approved these changes
👍

2019-01-24 21:48 UTC, jillo-abdullahi approved these changes
Looks okay to me 👍

2019-01-25 06:04 UTC, justmesam requested changes

2019-01-25 06:04 UTC, justmesam commented on src/actions/_test_/profileActions.test.js
> +    expect(actionCreators.getprofileSuccess(profileDetails).data).toEqual(
dispatch the actions using a mock store

2019-01-25 06:04 UTC, justmesam commented on src/setupProxy.js
> +// const proxy = require("http-proxy-middleware");
Why is this file commented? also its bad practice to push commented code.

2019-01-25 06:26 UTC, denomash commented on src/setupProxy.js
> +// const proxy = require("http-proxy-middleware");
Thanks for pointing that out let me delete it since we are using axiosConfig.

2019-01-25 06:26 UTC, denomash commented on src/actions/_test_/profileActions.test.js
> +    expect(actionCreators.getprofileSuccess(profileDetails).data).toEqual(
Let me look into it

2019-01-25 07:23 UTC, denomash commented on src/actions/_test_/profileActions.test.js
> +    expect(actionCreators.getprofileSuccess(profileDetails).data).toEqual(
I have implemented the feedback

2019-01-25 07:37 UTC, justmesam approved these changes

2019-01-25 07:37 UTC, merged