feat(comments): Implement comments
andela/ah-code-titans-frontend pull request #25
Opened 2019-01-24 10:11 UTC by davishooly

**What does this PR do?**
-  Comment article on the article page

**Description of tasks to be completed?**
- Create a comment section 

**How should this be manually tested?**
- Clone the repo and cd into the project root folder
- Switch to the relevant branch `git ft-comment-articles-161967094`
- Run `npm install` to update your packages.
- Start the server with `npm start`
- In your favorite browser, navigate to `http://localhost:3000`

**What are the relevant pivotal tracker stories?**
- [#161967094](https://www.pivotaltracker.com/story/show/161967094)

**Screenshots**
<img width="793" alt="screen shot 2019-01-24 at 13 10 19" src="https://user-images.githubusercontent.com/20512560/51671220-79013f80-1fd9-11e9-84c5-4590c6193723.png">

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2019-01-25 06:29 UTC, justmesam requested changes

2019-01-25 06:29 UTC, justmesam commented on src/api/commentsAPI.js
> +    return axios
why are you using axios rather than the instance created?

2019-01-25 06:29 UTC, justmesam commented on src/reducers/commentReducer.js
> +const commentReducer = (state = {}, action) => {
I think you should handle a get comments error rather than just success.

2019-01-25 06:29 UTC, justmesam commented on src/actions/commentsActions.js
> +  type: types.CREATE_ARTICLE_SUCCESS,
this action type is misleading

2019-01-25 07:21 UTC, davishooly commented on src/reducers/commentReducer.js
> +const commentReducer = (state = {}, action) => {
cool I'm working on that

2019-01-25 07:22 UTC, davishooly commented on src/api/commentsAPI.js
> +    return axios
I'm working on the changes

2019-01-25 07:26 UTC, davishooly commented on src/actions/commentsActions.js
> +  type: types.CREATE_ARTICLE_SUCCESS,
Thanks for catching that up

2019-01-28 16:19 UTC, denomash approved these changes
👍

2019-01-28 19:40 UTC, denomash requested changes
I've noted that it's difficult for users to spot comments with replies because they do not indicate(they all look the same). Kindly look into that. You can check for replies with comments and indicate like `view comments`

2019-01-28 20:00 UTC, Darius-Ndubi requested changes
When logged in and wishing to comment on an article I get this notification (screen shot below) but the comment is still added. 
![screenshot 2019-01-28 at 22 54 54](https://user-images.githubusercontent.com/16937341/51862775-64fa6c80-2350-11e9-898c-37a5de67a806.png)

2019-01-29 06:48 UTC, Darius-Ndubi approved these changes

2019-01-29 07:21 UTC, jillo-abdullahi requested changes
Hey @davishooly, Great stuff you've done here! A few further enhancements from my end. Is it possible that we have the reply text input field be a bit bigger? It would also be nice if the `View replies` button toggled to `Hide replies` when the replies have already been shown. One last thing, we can have a `Post reply` button instead of relying only on the Enter key.
<img width="701" alt="screenshot 2019-01-29 at 10 15 18" src="https://user-images.githubusercontent.com/25426934/51891002-cea96380-23ae-11e9-9fd6-97c76bf61151.png">

2019-01-29 07:27 UTC, davishooly commented
@denomash I have made the changes you requested you can update your local repo with my changes and test it out

2019-01-29 07:30 UTC, davishooly commented
@jillo-abdullahi cool working on that I will give you a heads up when I'm done working on the changes you have requested

2019-01-29 08:19 UTC, davishooly commented
@jillo-abdullahi All is good you can have a look at the changes

2019-01-29 08:56 UTC, denomash approved these changes

2019-01-29 12:37 UTC, jillo-abdullahi approved these changes

2019-01-29 12:41 UTC, Bryan-Cee approved these changes
👍 LGTM

2019-01-29 14:29 UTC, bettblake08 approved these changes

2019-01-30 14:31 UTC, merged