#161967111 Users can view their reading stats
andela/ah-code-titans-frontend pull request #29
Opened 2019-01-30 12:21 UTC by Bryan-Cee

2019-01-31 17:34 UTC, davishooly approved these changes

2019-01-31 17:36 UTC, denomash approved these changes
👍

2019-01-31 17:37 UTC, Darius-Ndubi approved these changes
👍

2019-02-01 00:44 UTC, justmesam requested changes

2019-02-01 00:44 UTC, justmesam commented on src/components/containers/profile/Profile.js
>    componentDidMount = () => {
Why do we have this as an arrow function?

2019-02-01 12:15 UTC, justmesam approved these changes

2019-02-01 12:15 UTC, merged